name: CI Tests

on:
  push:
    branches:
      - '**'  # all branches
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    # Reduce timeout to fail faster if stuck
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt

    - name: System health check
      run: |
        echo "=== System Info ==="
        uname -a
        df -h
        free -h
        ps aux | grep python || true
        echo "=== Python Info ==="
        which python
        python --version
        echo "=== Directory Info ==="
        pwd
        ls -la

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install test dependencies first with specific versions
        pip install 'pytest>=7.0.0' 'pytest-cov>=4.1.0'
        # Install the package in development mode
        pip install -e .
        # Install remaining dependencies
        pip install -r requirements-dev.txt
        playwright install --with-deps
        # Verify installations
        pip list
        # Debug: Show package location and Python path
        python -c "import resume_tailor; print(f'resume_tailor location: {resume_tailor.__file__}')"
        python -c "import sys; print('Python path:'); print('\n'.join(sys.path))"
        
    - name: Run tests and coverage
      id: tests
      # Add timeout to the test command itself
      run: |
        # Debug: Print current directory and contents
        pwd
        ls -la
        echo "=== Running Tests ==="
        # Run pytest with proper arguments
        timeout 180s pytest -v \
          --durations=0 \
          --tb=short \
          --showlocals \
          -x \
          tests/ \
          --cov=resume_tailor \
          --cov-fail-under=40 \
          --cov-report=term-missing || (echo "Tests timed out or failed" && exit 1)

    - name: Store coverage report
      if: always()  # Store even if tests fail
      run: |
        coverage report > coverage_report.txt || echo "No coverage report generated"
        
    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage_report.txt
        retention-days: 14 

    # Add explicit status check
    - name: Report status
      if: always()
      run: |
        if [[ "${{ steps.tests.outcome }}" == "success" ]]; then
          echo "All tests passed successfully!"
          exit 0
        else
          echo "Tests failed or timed out!"
          exit 1
        fi 